/*
 * qrng_measure.c -- real measured entropy + uniformity of the quantum_rng stream.
 *
 * Builds the core library (no LLVM needed) and reports the quantities that were
 * previously asserted by marketing text:
 *   - Shannon entropy of the output stream, in bits/byte (should be ~8.0).
 *   - Pearson chi-square uniformity statistic over 256 bins.
 *   - A runs test (up/down) loose sanity check.
 *
 * This is the audit's honest replacement for the retired "63.999872 bits/sample"
 * string and the broken qrng_get_entropy_estimate() (~1.3 bits/byte). The value
 * printed here is what qrng_get_entropy_estimate() now returns, computed from
 * the actual generated bytes.
 *
 * Build:
 *   gcc -std=c11 -O2 -Isrc -Isrc/quantum_rng qrng_measure.c \
 *       ../src/quantum_rng/quantum_rng.c ../src/common/secure_memory.c -o qrng_measure -lm
 *   ./qrng_measure
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "quantum_rng.h"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

static double chi2(const uint8_t *buf, size_t n) {
    long hist[256]; memset(hist, 0, sizeof(hist));
    for (size_t i = 0; i < n; i++) hist[buf[i]]++;
    double exp = (double)n / 256.0;
    double s = 0.0;
    for (int b = 0; b < 256; b++) {
        double d = (double)hist[b] - exp;
        s += d * d / exp;
    }
    return s; /* df=255, crit ~293.2 at p=0.05 */
}

int main(void) {
    qrng_ctx *ctx = NULL;
    /* Seeded -> reproducible stream. */
    uint8_t seed[4] = {0xDE, 0xAD, 0xBE, 0xEF};
    if (qrng_init(&ctx, seed, sizeof(seed)) != QRNG_SUCCESS) {
        fprintf(stderr, "qrng_init failed\n");
        return 1;
    }

    const size_t N = 1 << 16; /* 65536 bytes */
    uint8_t *buf = malloc(N);
    qrng_bytes(ctx, buf, N);

    double H = qrng_get_entropy_estimate(ctx);
    double x2 = chi2(buf, N);

    /* Runs test: count direction changes in the byte sequence. */
    long runs = 1;
    for (size_t i = 1; i < N; i++) {
        if ((buf[i] > buf[i-1]) != (buf[i-1] > buf[i-2 > 0 ? i-2 : 0])) runs++;
    }

    printf("qrng_measure (seeded 0xDEADBEEF, %zu bytes)\n", N);
    printf("  Shannon entropy      : %.4f bits/byte (max 8.0)\n", H);
    printf("  Chi-square uniformity: %.1f (df=255, crit~293 @ p=0.05)\n", x2);
    printf("  Runs (up/down)       : %ld\n", runs);
    /* Honest pass criteria: entropy must be near the 8 bits/byte max, and the
       chi-square uniformity statistic must be below the 0.05 critical value
       293.2 (df=255). The runs count is reported for context only — its naive
       expectation N/2 is not a hard threshold (direction-change runs in a
       uniform stream are autocorrelated and routinely land well above N/2). */
    int pass_entropy = (H > 7.9);
    int pass_uniform = (x2 < 293.2);
    printf("  Verdict: %s\n",
           (pass_entropy && pass_uniform) ? "uniform & high-entropy (pass)"
                                          : "FAIL uniformity/entropy");

    free(buf);
    qrng_free(ctx);
    return 0;
}
